### ISSUE TITLE
网格是否支持回测

### ISSUE THREAD

**Issue by 90hacker** [51bitquant/howtrader#10]
网格是否支持回测

**Comment by 51bitquant** [comment]
> 网格是否支持回测

回测跟网格没有什么关系的，只是我写内置的网格代码不支持网格回测而已，主要是网格代码用到了实盘引擎一些订阅资产的方法，以及用tick数据进行交易。 你可以改成基于分钟的网格。跟cta那种写法也是可以的。

**Comment by 51bitquant** [comment]
你可以参考网易云课堂VNPY的回测部分的讲解。由于里面的网格用的是实盘的tick数据，所以就没有支持回测。但是稍微修改成基于分钟bar的数据，就可以支持了，具体可以自己修改下。
