### ISSUE TITLE
cannot import name 'get_localzone_name' from 'tzlocal'   老师麻烦问下这个问题怎么解决 谢谢

### ISSUE THREAD

**Issue by daobaxiaozhi** [51bitquant/howtrader#15]
`C:\Users\admin\anaconda3\envs\howtrader-main\python.exe C:/Users/admin/strategies/btctest.py
Traceback (most recent call last):
  File "C:\Users\admin\strategies\btctest.py", line 1, in <module>
    from howtrader.app.cta_strategy import (
  File "E:\howtrader-main\howtrader\app\cta_strategy\__init__.py", line 4, in <module>
    from .base import APP_NAME, StopOrder
  File "E:\howtrader-main\howtrader\app\cta_strategy\base.py", line 11, in <module>
    from howtrader.trader.constant import Direction, Offset, Interval
  File "E:\howtrader-main\howtrader\trader\constant.py", line 7, in <module>
    from tzlocal import get_localzone_name
ImportError: cannot import name 'get_localzone_name' from 'tzlocal' (C:\Users\admin\anaconda3\envs\howtrader-main\lib\site-packages\tzlocal\__init__.py)`

**Comment by daobaxiaozhi** [comment]
tzlocal   pip卸载 重装 都试过了 不好使

**Comment by 51bitquant** [comment]
> `C:\Users\admin\anaconda3\envs\howtrader-main\python.exe C:/Users/admin/strategies/btctest.py Traceback (most recent call last): File "C:\Users\admin\strategies\btctest.py", line 1, in <module> from howtrader.app.cta_strategy import ( File "E:\howtrader-main\howtrader\app\cta_strategy\__init__.py", line 4, in <module> from .base import APP_NAME, StopOrder File "E:\howtrader-main\howtrader\app\cta_strategy\base.py", line 11, in <module> from howtrader.trader.constant import Direction, Offset, Interval File "E:\howtrader-main\howtrader\trader\constant.py", line 7, in <module> from tzlocal import get_localzone_name ImportError: cannot import name 'get_localzone_name' from 'tzlocal' (C:\Users\admin\anaconda3\envs\howtrader-main\lib\site-packages\tzlocal\__init__.py)`

安装最新的tzlocal, 4.2或者以上版本就可以. pip install tzlocal==4.2

**Comment by daobaxiaozhi** [comment]
谢谢老师
