### ISSUE TITLE
手动maker单不成功，一直submitting

### ISSUE THREAD

**Issue by yanfeng918** [51bitquant/howtrader#17]
![image](https://user-images.githubusercontent.com/19339846/179363384-a3cbf304-77e1-4410-8a6b-bbc2381aeada.png)

**Comment by 51bitquant** [comment]
The maker order is not supported yet, will support soon.

**Comment by 51bitquant** [comment]
> ![image](https://user-images.githubusercontent.com/19339846/179363384-a3cbf304-77e1-4410-8a6b-bbc2381aeada.png)

目前maker订订单还没支持，你可以使用limit,只要当前的价格低于市场价格，limit单就是maker单，后面会加上。

**Comment by yanfeng918** [comment]
我已经实现了，可以把代码提交上去吗

**Comment by yanfeng918** [comment]
自己每次升级后，都需要自己更改代码还是蛮麻烦的，另外，网格的时候，防止价格波动太大，我希望下maker单，也可以节省手续费。

**Comment by 51bitquant** [comment]
直接执行升级命令就可以了，还怎么改代码？------------------------------------------------------------------
***@***.***>
日　期：2022年07月19日 13:17:38
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [51bitquant/howtrader] 手动maker单不成功，一直submitting (Issue #17)

自己每次升级后，都需要自己更改代码还是蛮麻烦的，另外，网格的时候，防止价格波动太大，我希望下maker单，也可以节省手续费。

**Comment by 51bitquant** [comment]
> 自己每次升级后，都需要自己更改代码还是蛮麻烦的，另外，网格的时候，防止价格波动太大，我希望下maker单，也可以节省手续费。

直接通过命令行执行 pip install git+https://github.com/51bitquant/howtrader 就可以升级了。

just input the command in cmd/terminal: pip install git+https://github.com/51bitquant/howtrader,  then you can update to the new version.

**Comment by 51bitquant** [comment]
已经增加了maker 订单类型的支持。

**Comment by yanfeng918** [comment]
非常感谢，百忙之中能够完善代码
