### ISSUE TITLE
当成交后，收到account推送问题

### ISSUE THREAD

**Issue by yanfeng918** [51bitquant/howtrader#18]
![image](https://user-images.githubusercontent.com/19339846/182148872-bc941f5d-ff02-40a0-bf45-816f06fe00bd.png)
订阅现货资产，好像不能够生效；

这个云笔记总结，是我按照你以前视频完善的，希望能够进一步完善，
https://note.youdao.com/s/3BTbXtEB

**Comment by 51bitquant** [comment]
看这个文档： https://github.com/51bitquant/howtrader/blob/main/docs/%E5%A6%82%E4%BD%95%E8%AE%A2%E9%98%85%E4%BB%93%E4%BD%8D%E6%95%B0%E6%8D%AE.md

新的版本，已经分开了，改成了gate_way_name + '.' + 资产名称， 类似BINANCE_SPOT.USDT, BINANCE_SPOT.ETH, BINANCE_SPOT.BTC

**Comment by yanfeng918** [comment]
好的，谢谢，明白。
图片的代码，是从简单网格策略中找到的，直接打开注释发现，不能够使用
