### ISSUE TITLE
python main.py启动似乎异常

### ISSUE THREAD

**Issue by chenrenjing** [51bitquant/howtrader#29]
您好，我使用的操作系统是ubuntu20.04 server版本的，安装过程参考您的文档，最后启动的是这样的，这样是正常的吗
![image](https://user-images.githubusercontent.com/18564358/222072652-c64a8210-ebb0-468b-abba-dcd0b48bcab5.png)
![image](https://user-images.githubusercontent.com/18564358/222073349-37f52d99-358b-4f83-8572-ff810d2d8b37.png)

**Comment by chenrenjing** [comment]
![image](https://user-images.githubusercontent.com/18564358/222075326-6949e266-e921-4ed2-9407-b5f57f8c9cd7.png)
这个显示问题可以怎么处理

**Comment by 51bitquant** [comment]
> ![image](https://user-images.githubusercontent.com/18564358/222075326-6949e266-e921-4ed2-9407-b5f57f8c9cd7.png) 这个显示问题可以怎么处理

在项目下面的howtrader文件里面的vt_setting.json文件中，加上font.family字段，配置一个系统支持的字体。

**Comment by chenrenjing** [comment]
已经可以了

**Comment by 51bitquant** [comment]
> 您好，我使用的操作系统是ubuntu20.04 server版本的，安装过程参考您的文档，最后启动的是这样的，这样是正常的吗 ![image](https://user-images.githubusercontent.com/18564358/222072652-c64a8210-ebb0-468b-abba-dcd0b48bcab5.png) ![image](https://user-images.githubusercontent.com/18564358/222073349-37f52d99-358b-4f83-8572-ff810d2d8b37.png)

这个是提示其他UI库没有安装。
