### ISSUE TITLE
backtester

### ISSUE THREAD

**Issue by cangmohuyang** [51bitquant/howtrader#30]
你好，新代码为什么把ui的backtester删掉了，是因为有bug吗

**Comment by 51bitquant** [comment]
兼容性问题。

**Comment by 51bitquant** [comment]
直接回测是可以的。它会在浏览器展示结果。参考这个代码： https://github.com/51bitquant/howtrader/blob/main/examples/backtest_demo.py

**Comment by mraiguo** [comment]
UI 回测使用起来会方便点，考虑增加回去吗
