### ISSUE TITLE
对现货网格策略回测的时候出现报错：TypeError: 'NoneType' object is not callable，这个参数是需要添加什么？

### ISSUE THREAD

**Issue by aiyunwang1992** [51bitquant/howtrader#31]
![image](https://user-images.githubusercontent.com/48650925/226380828-4b9d8ffc-5d5c-4892-b8ff-b4549202e5d2.png)
![image](https://user-images.githubusercontent.com/48650925/226380986-de2f2db0-2bd7-4ac5-aa3f-8d03dda2369d.png)

**Comment by 51bitquant** [comment]
网格策略不支持回测导致的。

**Comment by 51bitquant** [comment]
网格策略用到实盘引擎导致不能回测，如果需要回测，参考回测的代码进行修改。
