### ISSUE TITLE
mainengine

### ISSUE THREAD

**Issue by xz3n14** [51bitquant/howtrader#34]
mainengine主引擎代码中少了一个get_contract的方法，converter.py里就有调用主引擎的get_contract方法

**Comment by 51bitquant** [comment]
> mainengine主引擎代码中少了一个get_contract的方法，converter.py里就有调用主引擎的get_contract方法

该方法在OmsEngine 里面
```
class OmsEngine(BaseEngine)

```

并通过 add_function 方法注册到mainEngine 里面。
