### ISSUE TITLE
请问下howtrader是基于vnpy哪个版本的？

### ISSUE THREAD

**Issue by chencore** [51bitquant/howtrader#5]
请问下howtrader是基于vnpy哪个版本的？怎么没有找到唐奇安通道指标计算的代码
`self.entry_up, self.entry_down = self.am.donchian(self.entry_window)`

**Comment by 51bitquant** [comment]
最新的版本，唐奇安通道指标计算的代码， 可以看example/strategies目录下面。为了方便实盘，把内置的策略放到了example里面了，你可以基于example/stratgies文件夹的策略修改。

**Comment by 51bitquant** [comment]
最新版本已经基于VNPY3.1开发了。里面功能跟vnpy基本一致。增加了网络断开下，持仓的同步和成交的细节处理。
